# Generated by Django 4.2 on 2024-12-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='name')),
                ('name_uz', models.CharField(blank=True, max_length=120, null=True, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='name')),
                ('name_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='name')),
                ('company_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='company_name')),
                ('company_name_uz', models.CharField(blank=True, max_length=120, null=True, verbose_name='company_name')),
                ('company_name_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='company_name')),
                ('company_name_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='company_name')),
                ('comment', models.TextField(verbose_name='comment')),
                ('comment_uz', models.TextField(null=True, verbose_name='comment')),
                ('comment_en', models.TextField(null=True, verbose_name='comment')),
                ('comment_ru', models.TextField(null=True, verbose_name='comment')),
                ('image', models.ImageField(upload_to='feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=120)),
                ('comment', models.TextField()),
                ('is_checked', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('title_uz', models.CharField(max_length=120, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=120, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=120, null=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_uz', models.TextField(null=True, verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_ru', models.TextField(null=True, verbose_name='description')),
                ('image', models.ImageField(upload_to='portfolio')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('title_uz', models.CharField(max_length=120, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=120, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=120, null=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_uz', models.TextField(null=True, verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_ru', models.TextField(null=True, verbose_name='description')),
                ('image', models.ImageField(upload_to='services')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='full_name')),
                ('full_name_uz', models.CharField(max_length=120, null=True, verbose_name='full_name')),
                ('full_name_en', models.CharField(max_length=120, null=True, verbose_name='full_name')),
                ('full_name_ru', models.CharField(max_length=120, null=True, verbose_name='full_name')),
                ('bio', models.TextField(verbose_name='bio')),
                ('bio_uz', models.TextField(null=True, verbose_name='bio')),
                ('bio_en', models.TextField(null=True, verbose_name='bio')),
                ('bio_ru', models.TextField(null=True, verbose_name='bio')),
                ('position', models.CharField(max_length=120, verbose_name='position')),
                ('position_uz', models.CharField(max_length=120, null=True, verbose_name='position')),
                ('position_en', models.CharField(max_length=120, null=True, verbose_name='position')),
                ('position_ru', models.CharField(max_length=120, null=True, verbose_name='position')),
                ('profile_image', models.ImageField(upload_to='profile_image')),
            ],
        ),
    ]
